ifndef SWITCHLIGHT
$(error $$SWITCHLIGHT is undefined.)
endif

SWITCHLIGHT_REQUIRED_SUBMODULES := ly2-sdk-5.10.0
SWITCHLIGHT_REQUIRED_PACKAGES := kernel-85xx-headers:powerpc

include $(SWITCHLIGHT)/make/component.mk




