
###############################################################################
#
# Inclusive Makefile for the sl module.
#
# Autogenerated 2013-08-30 15:07:23.093697
#
###############################################################################
sl_BASEDIR := $(dir $(abspath $(lastword $(MAKEFILE_LIST))))
include $(sl_BASEDIR)/module/make.mk
include $(sl_BASEDIR)/module/auto/make.mk
include $(sl_BASEDIR)/module/src/make.mk
include $(sl_BASEDIR)/utest/_make.mk

