ifndef SWITCHLIGHT
$(error $$SWITCHLIGHT is undefined.)
endif

# SWITCHLIGHT_REQUIRED_SUBMODULES := 
SWITCHLIGHT_REQUIRED_PACKAGES := vendor-config-switchlight:all vendor-config-dni:all

include $(SWITCHLIGHT)/make/component.mk
