#!/bin/bash -ex
############################################################
# <bsn.cl fy=2013 v=none>
#
#        Copyright 2013, 2014 BigSwitch Networks, Inc.
#
#
#
# </bsn.cl>
############################################################
WS_ROOT=$1

# Custom ofad symlinks
cp ofadsymlinks.py ${WS_ROOT}/etc/init.d

# User default release settings
. ${SWITCHLIGHT}/builds/swi/powerpc/release/rootfs/cleanup
