# -*- Makefile -*-
###############################################################################
#
# SDK 6.3.3 Internal Build Configuration
#
###############################################################################
SDK_CONFIG=internal
BUILD_SDK_6_3_3_DIR := $(abspath $(dir $(lastword $(MAKEFILE_LIST))))
include ../sdk-6.3.3.mk






