############################################################
# <bsn.cl fy=2013 v=none>
# 
#        Copyright 2013, 2014 BigSwitch Networks, Inc.        
# 
# 
# 
# </bsn.cl>
############################################################
ARCH=all
PACKAGE_NAMES=platform-config-powerpc-quanta-lb9-r0
DEBUILD_ARGS=-eSWITCHLIGHT_SUBMODULE_BROADCOM
include ../../../../../make/debuild.mk
