ifndef SWITCHLIGHT
$(error $$SWITCHLIGHT is undefined.)
endif

SWITCHLIGHT_REQUIRED_SUBMODULES := onlp
SWITCHLIGHT_REQUIRED_PACKAGES := onlp-platform:powerpc onlp-platform-defaults:powerpc

include $(SWITCHLIGHT)/make/component.mk
