#!/usr/bin/python
# -*- Python -*- 
import sys
import os
import socket
import traceback

#
# Issue a command to the ofad network cli. 
#

if len(sys.argv) == 1:
    print "usage: %s [command...]" % sys.argv[0]
    sys.exit(1)

# Default to localhost
server = "localhost"

# Allow override through environment
if os.getenv("SERVER"):
    server = os.getenv("SERVER")

try:
    s = socket.socket()
    s.connect((server, 4454))
    cmd = " ".join(sys.argv[1:]) + "\n"
    s.send(cmd)

    while True:
        data = s.recv(1024)
        if data:
            sys.stdout.write(data)
        else:
            break
    
    s.close()
    sys.exit(0)
except Exception as e:
    s.close()
    traceback.print_exc(None, None)
    sys.exit(1)

