ifndef SWITCHLIGHT
$(error $$SWITCHLIGHT is undefined.)
endif

# Fill me out if necessary
SWITCHLIGHT_REQUIRED_SUBMODULES := broadcom
SWITCHLIGHT_REQUIRED_PACKAGES := vendor-config-quanta:all

include $(SWITCHLIGHT)/make/component.mk
