# -*- Makefile -*-
############################################################
ifndef SWITCHLIGHT
$(error $$SWITCHLIGHT is not set)
endif

include $(SWITCHLIGHT)/make/config.mk

all:
	@echo Run 'make deb'

.PHONY: deb
deb:
	$(MAKE) -C deb
