
##############################################################################
#
# Builder Module Manifest.
#
# Autogenerated 2014-11-05 10:07:20.929533
#
##############################################################################
BASEDIR := $(dir $(lastword $(MAKEFILE_LIST)))
arpa_BASEDIR := $(BASEDIR)arpa
arpra_BASEDIR := $(BASEDIR)arpra
cdpa_BASEDIR := $(BASEDIR)cdpa
dhcpra_BASEDIR := $(BASEDIR)dhcpra
host_sflow_BASEDIR := $(BASEDIR)host_sflow
icmpa_BASEDIR := $(BASEDIR)icmpa
lacpa_BASEDIR := $(BASEDIR)lacpa
lldpa_BASEDIR := $(BASEDIR)lldpa
router_ip_table_BASEDIR := $(BASEDIR)router_ip_table
sflowa_BASEDIR := $(BASEDIR)sflowa
slshared_BASEDIR := $(BASEDIR)slshared


ALL_MODULES := $(ALL_MODULES) arpa arpra cdpa dhcpra host_sflow icmpa lacpa lldpa router_ip_table sflowa slshared
