
##############################################################################
#
# Builder Module Manifest.
#
# Autogenerated 2016-05-23 15:39:51.604306
#
##############################################################################
BASEDIR := $(dir $(lastword $(MAKEFILE_LIST)))
arpa_BASEDIR := $(BASEDIR)arpa
arpra_BASEDIR := $(BASEDIR)arpra
cdpa_BASEDIR := $(BASEDIR)cdpa
collecta_BASEDIR := $(BASEDIR)collecta
dhcpra_BASEDIR := $(BASEDIR)dhcpra
host_sflow_BASEDIR := $(BASEDIR)host_sflow
icmpa_BASEDIR := $(BASEDIR)icmpa
icmpv6_BASEDIR := $(BASEDIR)icmpv6
igmpa_BASEDIR := $(BASEDIR)igmpa
lacpa_BASEDIR := $(BASEDIR)lacpa
lldpa_BASEDIR := $(BASEDIR)lldpa
macblaster_BASEDIR := $(BASEDIR)macblaster
pdua_BASEDIR := $(BASEDIR)pdua
pktina_BASEDIR := $(BASEDIR)pktina
router_ip_table_BASEDIR := $(BASEDIR)router_ip_table
sflowa_BASEDIR := $(BASEDIR)sflowa
slshared_BASEDIR := $(BASEDIR)slshared
vxlan_BASEDIR := $(BASEDIR)vxlan


ALL_MODULES := $(ALL_MODULES) arpa arpra cdpa collecta dhcpra host_sflow icmpa icmpv6 igmpa lacpa lldpa macblaster pdua pktina router_ip_table sflowa slshared vxlan
