
###############################################################################
#
# Inclusive Makefile for the slshared module.
#
# Autogenerated 2015-03-11 10:05:32.822492
#
###############################################################################
slshared_BASEDIR := $(dir $(abspath $(lastword $(MAKEFILE_LIST))))
include $(slshared_BASEDIR)/module/make.mk
include $(slshared_BASEDIR)/module/src/make.mk
include $(slshared_BASEDIR)/module/auto/make.mk

