/**************************************************************************//**
 * 
 * 
 * 
 *****************************************************************************/
#include <AET/aet_config.h>

#if AET_CONFIG_INCLUDE_UCLI == 1

#include <uCli/ucli.h>
#include <uCli/ucli_argparse.h>
#include <uCli/ucli_handler_macros.h>

static ucli_status_t 
aet_ucli_ucli__config__(ucli_context_t* uc)
{
    UCLI_HANDLER_MACRO_MODULE_CONFIG(aet)
}

/* <auto.ucli.handlers.start> */
/******************************************************************************
 *
 * These handler table(s) were autogenerated from the symbols in this 
 * source file. 
 *
 *****************************************************************************/
static ucli_command_handler_f aet_ucli_ucli_handlers__[] = 
{
    aet_ucli_ucli__config__,
    NULL
};
/******************************************************************************/
/* <auto.ucli.handlers.end> */

static ucli_module_t
aet_ucli_module__ = 
    {
        "aet_ucli", 
        NULL,  
        aet_ucli_ucli_handlers__, 
        NULL, 
        NULL, 
    };

ucli_node_t*
aet_ucli_node_create(void)
{
    ucli_node_t* n; 
    ucli_module_init(&aet_ucli_module__); 
    n = ucli_node_create("aet", NULL, &aet_ucli_module__); 
    ucli_node_subnode_add(n, ucli_module_log_node_create("aet")); 
    return n; 
}

#else
void*
aet_ucli_node_create(void)
{
    return NULL; 
}
#endif

