
###############################################################################
#
# Inclusive Makefile for the pktina module.
#
# Autogenerated 2016-03-22 22:38:15.920473
#
###############################################################################
pktina_BASEDIR := $(dir $(abspath $(lastword $(MAKEFILE_LIST))))
include $(pktina_BASEDIR)/module/make.mk
include $(pktina_BASEDIR)/module/src/make.mk
include $(pktina_BASEDIR)/module/auto/make.mk
include $(pktina_BASEDIR)/utest/_make.mk

