############################################################
# <bsn.cl fy=2013 v=none>
#
#        Copyright 2013, 2014 BigSwitch Networks, Inc.
#
#
#
# </bsn.cl>
############################################################
ifndef SWITCHLIGHT
$(error $$SWITCHLIGHT is undefined.)
endif

SWITCHLIGHT_REQUIRED_SUBMODULES := \
	bigcode bigcode-internal broadcom indigo infra \
	loxigen-artifacts sdk-6.3.3 switchlight-common

include $(SWITCHLIGHT)/make/component.mk




