ifndef SWITCHLIGHT
$(error $$SWITCHLIGHT is undefined.)
endif

SWITCHLIGHT_REQUIRED_SUBMODULES := broadcom bigcode bigcode-internal indigo infra switchlight-common loxigen-artifacts
SWITCHLIGHT_REQUIRED_PACKAGES := libbroadcom-5.10-release-dev:powerpc
include $(SWITCHLIGHT)/make/component.mk




