ifndef SWITCHLIGHT
$(error $$SWITCHLIGHT is undefined.)
endif

# Fill me out if necessary
# SWITCHLIGHT_REQUIRED_SUBMODULES :=
SWITCHLIGHT_REQUIRED_PACKAGES := vendor-config-switchlight:all

include $(SWITCHLIGHT)/make/component.mk
