############################################################
# <bsn.cl fy=2013 v=none>
# 
#        Copyright 2013, 2014 BigSwitch Networks, Inc.        
# 
# 
# 
# </bsn.cl>
############################################################
ifndef SWITCHLIGHT
$(error $$SWITCHLIGHT is undefined.)
endif

# Fill me out if necessary
# SWITCHLIGHT_REQUIRED_SUBMODULES :=
SWITCHLIGHT_REQUIRED_PACKAGES := vendor-config-switchlight:all

include $(SWITCHLIGHT)/make/component.mk
