ifndef SWITCHLIGHT
$(error $$SWITCHLIGHT is undefined.)
endif

SWITCHLIGHT_REQUIRED_SUBMODULES := broadcom bigcode indigo bigcode-internal infra switchlight-common loxigen-artifacts
SWITCHLIGHT_REQUIRED_PACKAGES := libbroadcom-6.2-internal-dev:powerpc
include $(SWITCHLIGHT)/make/component.mk




