ifndef SWITCHLIGHT
$(error $$SWITCHLIGHT is undefined.)
endif

SWITCHLIGHT_REQUIRED_PACKAGES := kernel-85xx:powerpc \
				 kernel-85xx-dtbs:powerpc \
				 initrd-powerpc:powerpc \
			         platform-config-powerpc-quanta-lb9-r0:all \

include $(SWITCHLIGHT)/make/component.mk


