############################################################
# <bsn.cl fy=2013 v=none>
# 
#        Copyright 2013, 2014 BigSwitch Networks, Inc.        
# 
# 
# 
# </bsn.cl>
############################################################
ARCH=powerpc
PACKAGE_NAMES=platform-powerpc-as5610-52x
include ../../../../../make/debuild.mk



