/**************************************************************************//**
 *
 *
 *
 *****************************************************************************/
#include <sl/sl_config.h>

#if SL_CONFIG_INCLUDE_UCLI == 1

#include <uCli/ucli.h>
#include <uCli/ucli_argparse.h>
#include <uCli/ucli_handler_macros.h>

static ucli_status_t
sl_cat__(ucli_context_t* uc, const char* path)
{
    FILE* fp; 
    char b[256] = {0}; 

    if((fp = fopen(path, "r"))) { 
        while(fread(b, sizeof(char), sizeof(b), fp)) { 
            ucli_printf(uc, "%s", b); 
            memset(b, 0, sizeof(b)); 
        }
        fclose(fp); 
    }
    else {
        ucli_printf(uc, "unknown\n"); 
    }
    return UCLI_STATUS_OK; 
}
    
static ucli_status_t
sl_ucli_ucli__sl_version__(ucli_context_t* uc)
{
    UCLI_COMMAND_INFO(uc, 
                      "sl-version", 0, 
                      "$summary#Show SwitchLight version."); 
    return sl_cat__(uc, "/etc/sl_version"); 
}

static ucli_status_t
sl_ucli_ucli__sl_platform__(ucli_context_t* uc)
{
    UCLI_COMMAND_INFO(uc, 
                      "sl-platform", 0, 
                      "$summary#Show SwitchLight platform."); 
    return sl_cat__(uc, "/etc/sl_platform"); 
}

static ucli_status_t
sl_ucli_ucli__sl_swi__(ucli_context_t* uc)
{
    UCLI_COMMAND_INFO(uc, 
                      "sl-swi", 0, 
                      "$summary#Show SwitchLight SWI."); 
    return sl_cat__(uc, "/etc/sl_swi"); 
}


static ucli_status_t 
sl_ucli_ucli__config__(ucli_context_t* uc)
{
    UCLI_HANDLER_MACRO_MODULE_CONFIG(sl)
}


/* <auto.ucli.handlers.start> */
/******************************************************************************
 *
 * These handler table(s) were autogenerated from the symbols in this 
 * source file. 
 *
 *****************************************************************************/
static ucli_command_handler_f sl_ucli_ucli_handlers__[] = 
{
    sl_ucli_ucli__sl_version__, 
    sl_ucli_ucli__sl_platform__, 
    sl_ucli_ucli__sl_swi__, 
    sl_ucli_ucli__config__, 
    NULL
};
/******************************************************************************/
/* <auto.ucli.handlers.end> */

static ucli_module_t
sl_ucli_module__ = 
    {
        "sl_ucli", 
        NULL,  
        sl_ucli_ucli_handlers__, 
        NULL, 
        NULL, 
    };

ucli_node_t*
sl_ucli_node_create(void)
{
    ucli_node_t* n; 
    ucli_module_init(&sl_ucli_module__); 
    n = ucli_node_create("sl", NULL, &sl_ucli_module__); 
    ucli_node_subnode_add(n, ucli_module_log_node_create("sl")); 
    return n; 
}

#else
void*
sl_ucli_node_create(void)
{
    return NULL; 
}
#endif

