ifndef ARCH
$(error $$ARCH is not specified.)
endif

ifndef BUILD_DIR_BASE
$(error $$BUILD_DIR_BASE is not specified.)
endif

PACKAGE_NAMES=brcmd-5.6.6-sim brcmd-5.6.6-sim-dbg
include ../../../../../../make/debuild.mk



