
###############################################################################
#
# Inclusive Makefile for the igmpa module.
#
# Autogenerated 2015-07-22 00:04:10.322947
#
###############################################################################
igmpa_BASEDIR := $(dir $(abspath $(lastword $(MAKEFILE_LIST))))
include $(igmpa_BASEDIR)/module/make.mk
include $(igmpa_BASEDIR)/module/auto/make.mk
include $(igmpa_BASEDIR)/module/src/make.mk
include $(igmpa_BASEDIR)/utest/_make.mk

