
###############################################################################
#
# Inclusive Makefile for the vxlan module.
#
# Autogenerated 2016-03-29 21:36:23.647032
#
###############################################################################
vxlan_BASEDIR := $(dir $(abspath $(lastword $(MAKEFILE_LIST))))
include $(vxlan_BASEDIR)/module/make.mk
include $(vxlan_BASEDIR)/module/src/make.mk
include $(vxlan_BASEDIR)/module/auto/make.mk
include $(vxlan_BASEDIR)/utest/_make.mk

