############################################################
# <bsn.cl fy=2013 v=none>
#
#        Copyright 2013, 2014 BigSwitch Networks, Inc.
#
#
#
# </bsn.cl>
############################################################
ifndef SWITCHLIGHT
$(error $$SWITCHLIGHT is undefined.)
endif

SWITCHLIGHT_REQUIRED_SUBMODULES := sdk-6.3.3
SWITCHLIGHT_REQUIRED_PACKAGES := kernel-x86-64-headers:amd64

include $(SWITCHLIGHT)/make/component.mk




