#!/bin/bash -ex
LOCALDIR=$(dirname "$0")
SHARED_DIR=${LOCALDIR}/../../../all/shared
WS_ROOT=$1
tar -C "${SHARED_DIR}" -c --exclude "*~" . | tar -C "${WS_ROOT}" -x -v --no-same-owner

cp ${LOCALDIR}/ofad-baseconf-gus ${WS_ROOT}/etc/init.d/ofad-baseconf

chroot "${WS_ROOT}" /usr/sbin/update-rc.d initdev defaults
chroot "${WS_ROOT}" /usr/sbin/update-rc.d restorepersist defaults
chroot "${WS_ROOT}" /usr/sbin/update-rc.d rc.boot defaults
chroot "${WS_ROOT}" /usr/sbin/update-rc.d ofad-baseconf defaults
chroot "${WS_ROOT}" /usr/sbin/update-rc.d sensors-baseconf defaults
chroot "${WS_ROOT}" /usr/sbin/update-rc.d snmpd-baseconf defaults
chroot "${WS_ROOT}" /usr/sbin/update-rc.d faultd defaults
chroot "${WS_ROOT}" /usr/sbin/update-rc.d loadstartupconfig defaults
chroot "${WS_ROOT}" /usr/sbin/update-rc.d ofad defaults
chroot "${WS_ROOT}" /usr/sbin/update-rc.d snmpd remove
chroot "${WS_ROOT}" /usr/sbin/update-rc.d ssh defaults
chroot "${WS_ROOT}" /usr/sbin/update-rc.d openbsd-inetd remove
chroot "${WS_ROOT}" /usr/sbin/update-rc.d ntp remove
chroot "${WS_ROOT}" /usr/sbin/update-rc.d nfs-common remove
chroot "${WS_ROOT}" /usr/sbin/update-rc.d rpcbind remove
chroot "${WS_ROOT}" /usr/sbin/update-rc.d motd remove
chroot "${WS_ROOT}" /usr/sbin/update-rc.d kexec remove
chroot "${WS_ROOT}" /usr/sbin/update-rc.d kexec-load remove
chroot "${WS_ROOT}" /usr/sbin/update-rc.d mountall-bootclean.sh remove
chroot "${WS_ROOT}" /usr/sbin/update-rc.d mountall.sh remove
chroot "${WS_ROOT}" /usr/sbin/update-rc.d checkfs.sh remove
chroot "${WS_ROOT}" /usr/sbin/update-rc.d mtab.sh remove
chroot "${WS_ROOT}" /usr/sbin/update-rc.d checkroot-bootclean.sh remove
chroot "${WS_ROOT}" /usr/sbin/update-rc.d checkroot.sh remove
chroot "${WS_ROOT}" /usr/sbin/update-rc.d mountnfs-bootclean.sh remove
chroot "${WS_ROOT}" /usr/sbin/update-rc.d mountnfs.sh remove
chroot "${WS_ROOT}" /usr/sbin/update-rc.d lm-sensors remove

cat >>"${WS_ROOT}/tmp/rootpass.sh" <<EOF
#!/bin/bash
echo "Setting root password to 'bsn'"
echo root:bsn | /usr/sbin/chpasswd
EOF

chmod +x "${WS_ROOT}/tmp/rootpass.sh"
chroot "${WS_ROOT}" /tmp/rootpass.sh
rm "${WS_ROOT}/tmp/rootpass.sh"

rm -f "${WS_ROOT}/etc/securetty" # allow root login via telnet
sed -i "s/\(^[123456]:.*\)/#\1/" "${WS_ROOT}/etc/inittab"
echo "T0:23:respawn:/sbin/pgetty ttyS0" >>"${WS_ROOT}/etc/inittab"
: >"${WS_ROOT}/etc/motd"
echo "admin:x:0:0:root:/root:/usr/bin/pcli" >>"${WS_ROOT}/etc/passwd"
echo "admin::::::::" >>"${WS_ROOT}/etc/shadow"
chroot "${WS_ROOT}" /usr/bin/apt-get clean
chroot "${WS_ROOT}" /usr/sbin/localepurge
find "${WS_ROOT}/usr/share/doc" -type f | xargs rm -rf
find "${WS_ROOT}/usr/share/man" -type f | xargs rm -rf
