#!/bin/sh

n=1
dump() {
    echo "$2 port $n:"
    hexdump -C /sys/class/i2c-dev/i2c-$1/device/$1-0050/eeprom 2>/dev/null
    n=$((n+1))
}

# Linux assigns I2C bus numbers as it enumerates the I2C master/mux
# devices in the device tree breadth-first.  The bus numbers below may
# change if the device tree changes.

for i in $(seq 80 1 127); do
    dump $i SFP
done
for i in $(seq 16 1 63); do
    dump $i SFP
done
for i in $(seq 128 1 131); do
    dump $i QSFP
done
for i in $(seq 64 1 67); do
    dump $i QSFP
done
