############################################################
# <bsn.cl fy=2013 v=none>
# 
#        Copyright 2013, 2014 BigSwitch Networks, Inc.        
# 
# 
# 
# </bsn.cl>
############################################################
ARCH=all
PACKAGE_NAMES=libbroadcom-6.3-internal-src 
DEBUILD_ARGS=-eSDK

include ../../../../../make/debuild.mk



