############################################################
# <bsn.cl fy=2013 v=none>
# 
#        Copyright 2013, 2014 BigSwitch Networks, Inc.        
# 
# 
# 
# </bsn.cl>
############################################################
ARCH=powerpc
PACKAGE_NAMES=kernel-as-e500mc kernel-as-e500mc-headers kernel-as-e500mc-dtbs
include ../../../../../make/debuild.mk



