ifndef SWITCHLIGHT
$(error $$SWITCHLIGHT is undefined.)
endif

SWITCHLIGHT_REQUIRED_SUBMODULES := infra sl broadcom bigcode indigo bigcode-internal
SWITCHLIGHT_REQUIRED_PACKAGES := libbroadcom-5.6-internal-src:all
include $(SWITCHLIGHT)/make/component.mk




