# -*- Makefile -*-
###########################################################################
#
#
###############################################################################
ifndef SWITCHLIGHT
$(error $$SWITCHLIGHT not defined.)
else
include $(SWITCHLIGHT)/make/config.mk
endif

export TOOLCHAIN=powerpc-linux-gnu

all:
	$(MAKE) -C $(SWITCHLIGHT_SUBMODULE_SL)/targets/sofcon
	cp $(SWITCHLIGHT_SUBMODULE_SL)/targets/sofcon/build/powerpc-linux-gnu/bin/sofcon .

.PHONY: deb

deb:
	$(MAKE) -C deb
