###############################################################################
#
# 
#
###############################################################################
MODULE := sl
AUTOMODULE := sl
ifndef BUILDER
$(error "$$BUILDER must be specified.")
endif
include $(BUILDER)/definemodule.mk
