############################################################
# <bsn.cl fy=2013 v=none>
#
#        Copyright 2013, 2014 BigSwitch Networks, Inc.
#
#
#
# </bsn.cl>
############################################################
############################################################
#
# Switchlight i386 VM Internal Build
#
############################################################
ROOTFS_BUILD_DIR := $(abspath $(dir $(lastword $(MAKEFILE_LIST))))
ROOTFS_ARCH := amd64
include $(SWITCHLIGHT)/make/rootfs.mk

