ifndef SWITCHLIGHT
$(error $$SWITCHLIGHT is undefined.)
endif

SWITCHLIGHT_REQUIRED_SUBMODULES := broadcom bigcode bigcode-internal
SWITCHLIGHT_REQUIRED_PACKAGES := libbroadcom-5.10-internal-dev:powerpc
include $(SWITCHLIGHT)/make/component.mk




