ifndef SWITCHLIGHT
$(error $$SWITCHLIGHT is undefined.)
endif

SWITCHLIGHT_REQUIRED_SUBMODULES := broadcom infra bigcode
SWITCHLIGHT_REQUIRED_PACKAGES := libbroadcom-6.3-release-dev:powerpc

include $(SWITCHLIGHT)/make/component.mk
