############################################################
# <bsn.cl fy=2013 v=none>
#
#        Copyright 2013, 2014 BigSwitch Networks, Inc.
#
#
#
# </bsn.cl>
############################################################
ARCH=amd64
PACKAGE_NAMES=libbroadcom-6.3-kernel-x86-64-modules
DEBUILD_ARGS=-eSDK
include ../../../../../../../make/debuild.mk



