############################################################
# <bsn.cl fy=2013 v=none>
# 
#        Copyright 2013, 2014 BigSwitch Networks, Inc.        
# 
# 
# 
# </bsn.cl>
############################################################
ifndef SWITCHLIGHT
$(error $$SWITCHLIGHT is undefined.)
endif

SWITCHLIGHT_REQUIRED_SUBMODULES := broadcom bigcode bigcode-internal indigo infra switchlight-common loxigen-artifacts
SWITCHLIGHT_REQUIRED_PACKAGES := libbroadcom-6.2-release-dev:powerpc
include $(SWITCHLIGHT)/make/component.mk




