ifndef SWITCHLIGHT
$(error $$SWITCHLIGHT is undefined.)
endif

SWITCHLIGHT_REQUIRED_SUBMODULES := broadcom bigcode
SWITCHLIGHT_REQUIRED_PACKAGES := libbroadcom-6.2-release-dev:powerpc
include $(SWITCHLIGHT)/make/component.mk




