############################################################
# <bsn.cl fy=2013 v=none>
#
#        Copyright 2013, 2014 BigSwitch Networks, Inc.
#
#
#
# </bsn.cl>
############################################################
ARCH=powerpc
PACKAGE_NAMES=libbroadcom-6.3-kernel-as-e500mc-modules
DEBUILD_ARGS=-eSDK
include ../../../../../../../make/debuild.mk



