############################################################
# <bsn.cl fy=2013 v=none>
#
#        Copyright 2013, 2014 BigSwitch Networks, Inc.
#
#
#
# </bsn.cl>
############################################################
ifndef SWITCHLIGHT
$(error $$SWITCHLIGHT is undefined.)
endif

SWITCHLIGHT_REQUIRED_SUBMODULES := broadcom bigcode infra bigcode-internal onlp
SWITCHLIGHT_REQUIRED_PACKAGES := libbroadcom-6.3-internal-dev:powerpc onlp:powerpc
include $(SWITCHLIGHT)/make/component.mk




