ifndef SWITCHLIGHT
$(error $$SWITCHLIGHT is undefined.)
endif

SWITCHLIGHT_REQUIRED_SUBMODULES := broadcom bigcode infra bigcode-internal
SWITCHLIGHT_REQUIRED_PACKAGES := libbroadcom-6.3-internal-dev:powerpc
include $(SWITCHLIGHT)/make/component.mk




