############################################################
# <bsn.cl fy=2013 v=none>
#
#        Copyright 2013, 2014 BigSwitch Networks, Inc.
#
#
#
# </bsn.cl>
############################################################
ARCH=powerpc
PACKAGE_NAMES=ofad-6.3.3-release-t5
export DEB_BUILD_OPTIONS=nostrip
DEBUILD_ARGS=-eDEB_BUILD_OPTIONS
include ../../../../../../make/debuild.mk



