#!/bin/sh
#
# netplug - policy agent for netplugd
#
# Copyright 2003 Key Research, Inc.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License, version 2, as
# published by the Free Software Foundation.  You are forbidden from
# redistributing or modifying it under the terms of any other license,
# including other versions of the GNU General Public License.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.


PATH=/usr/bin:/bin:/usr/sbin:/sbin
export PATH

dev="$1"
action="$2"

case "$action" in
in)
    #start the dhcp client if dhcp is enabled on the interface
    FILE="/etc/sl-dhcp-enabled-${dev}"
    if [ -e $FILE ]; then
        exec dhclient -4 -e IF_METRIC=100 -pf /var/run/dhclient.${dev}.pid -lf /var/lib/dhcp/dhclient.${dev}.leases -1 ${dev} 2>&1
    fi
    ;;
out)
    #stop the dhcp client if dhcp is enabled on the interface
    FILE="/etc/sl-dhcp-enabled-${dev}"
    if [ -e $FILE ]; then
        exec dhclient -r -pf /var/run/dhclient.${dev}.pid 2>&1
    fi
    ;;
probe)
    ;;
*)
    echo "I have been called with a funny action of '%s'!" 1>&2
    exit 1
    ;;
esac
