ifndef SWITCHLIGHT
$(error $$SWITCHLIGHT is undefined.)
endif

SWITCHLIGHT_REQUIRED_SUBMODULES := sdk-6.3.3
SWITCHLIGHT_REQUIRED_PACKAGES := kernel-85xx-headers:powerpc

include $(SWITCHLIGHT)/make/component.mk




