ifndef SWITCHLIGHT
$(error $$SWITCHLIGHT is undefined.)
endif

SWITCHLIGHT_REQUIRED_SUBMODULES := broadcom infra bigcode bigcode-internal
SWITCHLIGHT_REQUIRED_PACKAGES := libbroadcom-6.3-internal-dev:powerpc

include $(SWITCHLIGHT)/make/component.mk
