# -*- Makefile -*-
###############################################################################
#
# SDK 6.2.7 Internal Build Configuration
#
###############################################################################
SDK_CONFIG=internal
BUILD_SDK_6_2_7_DIR := $(abspath $(dir $(lastword $(MAKEFILE_LIST))))
include ../sdk-6.2.7.mk






