
##############################################################################
#
# Builder Module Manifest.
#
# Autogenerated 2013-10-09 14:00:31.855876
#
##############################################################################
BASEDIR := $(dir $(lastword $(MAKEFILE_LIST)))
IVS_BASEDIR := $(BASEDIR)IVS
sl_BASEDIR := $(BASEDIR)sl
sofc_BASEDIR := $(BASEDIR)sofc
AET_BASEDIR := $(BASEDIR)AET
ivd_BASEDIR := $(BASEDIR)ivd


ALL_MODULES := $(ALL_MODULES) sofc sl AET IVS ivd
