
##############################################################################
#
# Builder Module Manifest.
#
# Autogenerated 2013-10-09 13:51:08.946660
#
##############################################################################
BASEDIR := $(dir $(lastword $(MAKEFILE_LIST)))
sl_BASEDIR := $(BASEDIR)sl
AET_BASEDIR := $(BASEDIR)AET


ALL_MODULES := $(ALL_MODULES) AET sl
