ifndef SWITCHLIGHT
$(error $$SWITCHLIGHT is undefined.)
endif

SWITCHLIGHT_REQUIRED_SUBMODULES := bigcode infra
# SWITCHLIGHT_REQUIRED_PACKAGES :=

ARCH := powerpc
TOOLCHAIN := powerpc-linux-gnu

include $(SWITCHLIGHT)/make/component.mk
