#!/bin/bash -ex
############################################################
# <bsn.cl fy=2013 v=none>
#
#        Copyright 2013, 2014 BigSwitch Networks, Inc.
#
#
#
# </bsn.cl>
############################################################
LOCALDIR=$(dirname "$0")
SHARED_DIR=${LOCALDIR}/../../../all/shared
WS_ROOT=$1

HRFSTOOL="python ${SWITCHLIGHT}/tools/py/rfstool.py"
RFSTOOL="${HRFSTOOL} --chroot ${WS_ROOT}"

${HRFSTOOL} -c overlay "${SHARED_DIR}" "${WS_ROOT}"
chroot "${WS_ROOT}" /usr/sbin/update-rc.d initdev defaults
chroot "${WS_ROOT}" /usr/sbin/update-rc.d restorepersist remove
chroot "${WS_ROOT}" /usr/sbin/update-rc.d rc.boot defaults
chroot "${WS_ROOT}" /usr/sbin/update-rc.d platform-baseconf defaults
chroot "${WS_ROOT}" /usr/sbin/update-rc.d ofad-baseconf defaults
chroot "${WS_ROOT}" /usr/sbin/update-rc.d sensors-baseconf defaults
chroot "${WS_ROOT}" /usr/sbin/update-rc.d snmpd-baseconf defaults
chroot "${WS_ROOT}" /usr/sbin/update-rc.d faultd defaults
chroot "${WS_ROOT}" /usr/sbin/update-rc.d loadstartupconfig defaults
chroot "${WS_ROOT}" /usr/sbin/update-rc.d ofad defaults
chroot "${WS_ROOT}" /usr/sbin/update-rc.d snmpd remove
chroot "${WS_ROOT}" /usr/sbin/update-rc.d ssh remove
chroot "${WS_ROOT}" /usr/sbin/update-rc.d slrest defaults
chroot "${WS_ROOT}" /usr/sbin/update-rc.d openbsd-inetd remove
chroot "${WS_ROOT}" /usr/sbin/update-rc.d ntp remove
chroot "${WS_ROOT}" /usr/sbin/update-rc.d nfs-common remove
chroot "${WS_ROOT}" /usr/sbin/update-rc.d rpcbind remove
chroot "${WS_ROOT}" /usr/sbin/update-rc.d motd remove
chroot "${WS_ROOT}" /usr/sbin/update-rc.d kexec remove
chroot "${WS_ROOT}" /usr/sbin/update-rc.d kexec-load remove
chroot "${WS_ROOT}" /usr/sbin/update-rc.d mountall-bootclean.sh remove
chroot "${WS_ROOT}" /usr/sbin/update-rc.d mountall.sh remove
chroot "${WS_ROOT}" /usr/sbin/update-rc.d checkfs.sh remove
chroot "${WS_ROOT}" /usr/sbin/update-rc.d mtab.sh remove
chroot "${WS_ROOT}" /usr/sbin/update-rc.d checkroot-bootclean.sh remove
chroot "${WS_ROOT}" /usr/sbin/update-rc.d checkroot.sh remove
chroot "${WS_ROOT}" /usr/sbin/update-rc.d mountnfs-bootclean.sh remove
chroot "${WS_ROOT}" /usr/sbin/update-rc.d mountnfs.sh remove
chroot "${WS_ROOT}" /usr/sbin/update-rc.d lm-sensors remove
chroot "${WS_ROOT}" /usr/sbin/update-rc.d netplug defaults


# Root is disabled completely in release images
${RFSTOOL} -c user_disable root
# Standard admin and recovery accounts
${RFSTOOL} -c user_recovery_add standard
${RFSTOOL} -c user_admin_add

rm -f "${WS_ROOT}/etc/securetty" # allow root login via telnet
sed -i "s/\(^[123456]:.*\)/#\1/" "${WS_ROOT}/etc/inittab"
echo "T0:23:respawn:/sbin/pgetty ttyS0" >>"${WS_ROOT}/etc/inittab"

${RFSTOOL} -c fsclean

