############################################################
# <bsn.cl fy=2013 v=none>
# 
#        Copyright 2013, 2014 BigSwitch Networks, Inc.        
# 
# 
# 
# </bsn.cl>
############################################################
############################################################
#
# Switchlight Powerpc Release Filesystem
#
############################################################
ROOTFS_BUILD_DIR := $(abspath $(dir $(lastword $(MAKEFILE_LIST))))
ROOTFS_ARCH := powerpc
include $(SWITCHLIGHT)/make/rootfs.mk

