#!/usr/bin/python

### BEGIN INIT INFO
# Provides:        platform-baseconf
# Required-Start:  initdev
# Required-Stop:
# Default-Start:   S
# Default-Stop:
# Short-Description: Set up platform
### END INIT INFO

import sys
import os
from switchlight.platform.base import *
from switchlight.platform.current import SwitchLightPlatform
import shutil

platform=SwitchLightPlatform()

sys.stderr.write("Setting up base platform configuration for %s...\n" %
                 platform.platform())
sys.stderr.flush()

DEFAULT_ONLP_LIB = "/lib/powerpc-linux-gnu/libonlp-platform.so.1"
PLATFORM_ONLP_LIB = "%s/lib/libonlp-%s.so" % (platform.platform_basedir(), platform.platform())

if os.path.exists(PLATFORM_ONLP_LIB):
    if os.path.exists(DEFAULT_ONLP_LIB):
        os.unlink(DEFAULT_ONLP_LIB)
    sys.stderr.write("    %s -> %s\n" % (DEFAULT_ONLP_LIB, PLATFORM_ONLP_LIB))
    sys.stderr.flush()
    os.symlink(PLATFORM_ONLP_LIB, DEFAULT_ONLP_LIB)

shutil.copyfile("/etc/sl_platform", "/etc/onl_platform")

ONLPDUMP = "%s/bin/onlpdump" % (platform.platform_basedir())

if os.path.exists(ONLPDUMP):
    os.system("%s -o -j > /etc/.onie.json" % ONLPDUMP)

os.symlink(platform.platform_basedir(), "/lib/platform-config/current")

sys.stderr.write("Setting up base platform configuration for %s: done\n" %
                 platform.platform())

