#!/usr/bin/python

### BEGIN INIT INFO
# Provides:        snmpd-baseconf
# Required-Start:  initdev
# Required-Stop:
# Default-Start:   S
# Default-Stop:
# Short-Description: Set up snmpd.conf
### END INIT INFO

import sys

from switchlight.platform.base import *
from switchlight.platform.current import SwitchLightPlatform

platform=SwitchLightPlatform()

sys.stderr.write("Setting up base snmpd configuration...")
sys.stderr.flush()

sysDescr = open("/etc/sl_version").read()

def write_snmpd_conf(f):
    f.write("""############################################################\n""")
    f.write("""#\n""")
    f.write("""# SNMP Configuration\n""")
    f.write("""#\n""");
    f.write("""############################################################\n""");
    f.write("""\n""");
    f.write("""sysDescr %s""" % sysDescr)
    f.write("""sysLocation Not set\n""")
    f.write("""sysContact Not set\n""")
    f.write("""sysObjectId %s\n""" % platform.sys_object_id())
    f.write("""\n""");
    f.write("""agentSecName disman\n""")
    f.write("""createUser disman MD5 "internal user for monitoring"\n""")
    f.write("""rouser disman auth\n""")
    f.write("""\n""");
    f.write("""# Number of ifIndexes on this platform\n""")
    f.write("""override .1.3.6.1.2.1.2.1.0 integer %s""" % platform.ifnumber())
    f.write("""\n""");
    f.write("""# Enable sub-agents\n""");
    f.write("""master agentx\n""");
    f.flush()

f = sys.stderr if 'test' in sys.argv else open("/etc/snmp/snmpd.conf", "w")
write_snmpd_conf(f)
sys.stderr.write("done.\n")
