#!/bin/sh

### BEGIN INIT INFO
# Provides:        snmpd-baseconf
# Required-Start:  initdev
# Required-Stop:   
# Default-Start:   S
# Default-Stop:    
# Short-Description: Set up snmpd.conf
### END INIT INFO

. /lib/lsb/init-functions

log_action_begin_msg "Setting up base snmpd configuration"

unset descr
descr=$(cat /etc/sl_version 2>/dev/null)

cat >/etc/snmp/snmpd.conf <<EOF
# System information
sysDescr ${descr}
sysLocation Not set
sysContact Not set

# Access control
rocommunity public

agentSecName disman
createUser disman MD5 "internal user for monitoring"
rouser disman auth

# Default settings for temperature traps
monitor temp .1.3.6.1.4.1.2021.13.16.2.1.3 > 55000

# Default settings for fan traps
monitor -I fan1 .1.3.6.1.4.1.2021.13.16.3.1.3.1 < 2000
monitor -I fan2 .1.3.6.1.4.1.2021.13.16.3.1.3.2 < 2000
monitor -I fan3 .1.3.6.1.4.1.2021.13.16.3.1.3.3 < 2000
monitor -I fan4 .1.3.6.1.4.1.2021.13.16.3.1.3.4 < 2000
monitor -I fan5 .1.3.6.1.4.1.2021.13.16.3.1.3.13 < 1000

# Enable sub-agents
master agentx
EOF
