ifndef SWITCHLIGHT
$(error $$SWITCHLIGHT is undefined.)
endif

SWITCHLIGHT_REQUIRED_SUBMODULES := broadcom bigcode indigo bigcode-internal infra loxigen-artifacts
SWITCHLIGHT_REQUIRED_PACKAGES := libbroadcom-5.6-internal-dev:powerpc
include $(SWITCHLIGHT)/make/component.mk




