############################################################
# <bsn.cl fy=2013 v=none>
# 
#        Copyright 2013, 2014 BigSwitch Networks, Inc.        
# 
# 
# 
# </bsn.cl>
############################################################
ARCH=powerpc
PACKAGE_NAMES=kernel-as6700 kernel-as6700-headers kernel-as6700-dtbs
include ../../../../../make/debuild.mk



