############################################################
# <bsn.cl fy=2013 v=none>
# 
#        Copyright 2013, 2014 BigSwitch Networks, Inc.        
# 
# 
# 
# </bsn.cl>
############################################################
ARCH=amd64
PACKAGE_NAMES=libbroadcom-6.3-release libbroadcom-6.3-release-dev
DEBUILD_ARGS=-eSDK
include ../../../../../../../make/debuild.mk



