ifndef SWITCHLIGHT
$(error $$SWITCHLIGHT is undefined.)
endif

SWITCHLIGHT_REQUIRED_SUBMODULES := lb9-sdk-5.6.6
SWITCHLIGHT_REQUIRED_PACKAGES := kernel-85xx-headers:powerpc

include $(SWITCHLIGHT)/make/component.mk




