# -*- Makefile -*-
############################################################
ifndef SWITCHLIGHT
$(error $$SWITCHLIGHT is not set)
endif

include $(SWITCHLIGHT)/make/config.mk

all:
	@echo Nothing to be done.

.PHONY: deb
deb:
	$(MAKE) -C deb
