############################################################
# <bsn.cl fy=2013 v=none>
# 
#        Copyright 2013, 2014 BigSwitch Networks, Inc.        
# 
# 
# 
# </bsn.cl>
############################################################
ifndef SWITCHLIGHT
$(error $$SWITCHLIGHT is undefined.)
endif

SWITCHLIGHT_REQUIRED_PACKAGES := kernel-as6700:powerpc \
				 kernel-as6700-dtbs:powerpc \
				 initrd-powerpc:powerpc

include $(SWITCHLIGHT)/make/component.mk


