ifndef SWITCHLIGHT
$(error $$SWITCHLIGHT is undefined.)
endif

SWITCHLIGHT_REQUIRED_PACKAGES := kernel-as6700:powerpc \
				 kernel-as6700-dtbs:powerpc \
				 initrd-powerpc:powerpc

include $(SWITCHLIGHT)/make/component.mk


