
###############################################################################
#
# Inclusive Makefile for the collecta module.
#
# Autogenerated 2016-05-23 15:39:51.450867
#
###############################################################################
collecta_BASEDIR := $(dir $(abspath $(lastword $(MAKEFILE_LIST))))
include $(collecta_BASEDIR)/module/make.mk
include $(collecta_BASEDIR)/module/src/make.mk
include $(collecta_BASEDIR)/module/auto/make.mk
include $(collecta_BASEDIR)/utest/_make.mk

