############################################################
# <bsn.cl fy=2013 v=none>
# 
#        Copyright 2013, 2014 BigSwitch Networks, Inc.        
# 
# 
# 
# </bsn.cl>
############################################################
ARCH=all
PACKAGE_NAMES=platform-config-powerpc-as6700-32x-r0
include ../../../../../make/debuild.mk
