############################################################
# <bsn.cl fy=2013 v=none>
#
#        Copyright 2013, 2014 BigSwitch Networks, Inc.
#
#
#
# </bsn.cl>
############################################################
ifndef SWITCHLIGHT
$(error $$SWITCHLIGHT is undefined.)
endif

SWITCHLIGHT_REQUIRED_PACKAGES := kernel-e500mc:powerpc \
				 kernel-e500mc-dtbs:powerpc \
				 initrd-powerpc:powerpc

include $(SWITCHLIGHT)/make/component.mk


