# -*- Makefile -*-
############################################################
# <bsn.cl fy=2013 v=none>
# 
#        Copyright 2013, 2014 BigSwitch Networks, Inc.        
# 
# 
# 
# </bsn.cl>
############################################################
ifndef SWITCHLIGHT
$(error $$SWITCHLIGHT is not set)
endif

include $(SWITCHLIGHT)/make/config.mk

all: 
	@echo Run 'make deb'

.PHONY: deb
deb:
	$(MAKE) -C deb
