############################################################
# <bsn.cl fy=2013 v=none>
# 
#        Copyright 2013, 2014 BigSwitch Networks, Inc.        
# 
# 
# 
# </bsn.cl>
############################################################
ARCH=powerpc
PACKAGE_NAMES=libbroadcom-6.2-internal libbroadcom-6.2-internal-dev
DEBUILD_ARGS=-eSDK
include ../../../../../../../make/debuild.mk



