
###############################################################################
#
# Inclusive Makefile for the sofc module.
#
# Autogenerated 2013-05-22 10:52:22.751250
#
###############################################################################
sofc_BASEDIR := $(dir $(abspath $(lastword $(MAKEFILE_LIST))))
include $(sofc_BASEDIR)/module/make.mk
include $(sofc_BASEDIR)/module/src/make.mk
include $(sofc_BASEDIR)/module/auto/make.mk
include $(sofc_BASEDIR)/utest/_make.mk

