#!/bin/bash
############################################################
# <bsn.cl fy=2013 v=none>
# 
#        Copyright 2013, 2014 BigSwitch Networks, Inc.        
# 
# 
# 
# </bsn.cl>
############################################################
#
# Change into a SwitchLight workspace.
#
############################################################

WS_ROOT=.
while [ ! -f "${WS_ROOT}/.pandora-ws" ]; do
    if [ "${WS_ROOT}" -ef / ]; then
	echo "Must run within a pandora workspace" 2>&1
	exit 1
    fi
    WS_ROOT="${WS_ROOT}/.."
done
export WS_ROOT=$(realpath "${WS_ROOT}")
export OPENSSL_ppccap=0
sudo update-binfmts --enable

if [ $# -lt 1 ]; then
    set -- bash
fi

isolate -c $(dirname "$0")/chws-child -o "${WS_ROOT}" "$@"
