#!/bin/bash

LOADER_SIZE_KB=$1
LOADER=$2
FLASHFS=$3
FLASH_IMAGE=$4

if [ ! "${FLASH_IMAGE}" ]; then
    echo "Usage: $0 LOADER_SIZE_KB LOADER FLASHFS FLASH_IMAGE" >&2
    exit 1
fi

d=$(mktemp -d)
trap "rm -fr $d" 0 1

set -x

# Copy loader to flash image, add padding
cat ${LOADER} >${FLASH_IMAGE}
dd of=${FLASH_IMAGE} seek=${LOADER_SIZE_KB} bs=1024 count=0

# append flashfs
cat $FLASHFS >>${FLASH_IMAGE}

exit 0
