#!/bin/bash -e
############################################################
# <bsn.cl fy=2013 v=none>
# 
#        Copyright 2013, 2014 BigSwitch Networks, Inc.        
# 
# 
# 
# </bsn.cl>
############################################################
#
# swiver
#
# Update the version file in a SWI image.
#
############################################################

swi=$1
newswi=$2
version=$3

[ "${version}" ] || { echo "Usage: $0 SWI NEWSWI VERSION" >&2; exit 1; }

d=$(mktemp -d)
cp "${swi}" $d/swi.zip
echo "${version}" >$d/version
( cd $d; zip swi.zip version )
mv $d/swi.zip "${newswi}"
