/**************************************************************************//**
 *
 *
 *
 *****************************************************************************/
#include <collecta/collecta_config.h>
#include "collecta_log.h"
#include "collecta_int.h"

#if COLLECTA_CONFIG_INCLUDE_UCLI == 1

#include <uCli/ucli.h>
#include <uCli/ucli_argparse.h>
#include <uCli/ucli_handler_macros.h>

static ucli_status_t
collecta_ucli_ucli__clear_counters__(ucli_context_t* uc)
{
    UCLI_COMMAND_INFO(uc,
                      "clear", 0,
                      "$summary#Clear counters.");

    debug_counter_reset(&collect_counters.packet_in);
    debug_counter_reset(&collect_counters.packet_out);

    return UCLI_STATUS_OK;
}

static ucli_status_t
collecta_ucli_ucli__show_counters__(ucli_context_t* uc)
{
    UCLI_COMMAND_INFO(uc,
                      "counters", 0,
                      "$summary#Display counters.");

    ucli_printf(uc, "*************DUMPING COUNTERS*************\n");
    ucli_printf(uc, "TOTAL SAMPLES RECV'D       : %" PRId64 "\n",
                debug_counter_get(&collect_counters.packet_in));
    ucli_printf(uc, "TOTAL DATAGRAMS SENT       : %" PRId64 "\n",
                debug_counter_get(&collect_counters.packet_out));
    ucli_printf(uc, "*************END DUMPING COUNTERS**********\n");

    return UCLI_STATUS_OK;
}

static ucli_status_t
collecta_ucli_ucli__show_collectors__(ucli_context_t* uc)
{
    list_head_t *list = collect_collectors_list();
    list_links_t *cur;

    UCLI_COMMAND_INFO(uc,
                      "collectors", 0,
                      "$summary#Display collect collector entries.");

    if (list_empty(list)) return UCLI_STATUS_OK;

    ucli_printf(uc, "IP\t --> MAC\t\t PORT\t STATS(tx-pkts: tx-bytes)\n");
    LIST_FOREACH(list, cur) {
        collect_collector_entry_t *entry = container_of(cur, links,
                                                      collect_collector_entry_t);
        ucli_printf(uc, "%{ipv4a} --> %u\t %" PRId64 " : %" PRId64 "\n",
                    entry->key.collector_ip,
                    entry->value.collector_udp_dport,
                    entry->stats.tx_packets,entry->stats.tx_bytes);
    }

    return UCLI_STATUS_OK;
}

static ucli_status_t
collecta_ucli_ucli__config__(ucli_context_t* uc)
{
    UCLI_HANDLER_MACRO_MODULE_CONFIG(collecta)
}

/* <auto.ucli.handlers.start> */
/******************************************************************************
 *
 * These handler table(s) were autogenerated from the symbols in this
 * source file.
 *
 *****************************************************************************/
static ucli_command_handler_f collecta_ucli_ucli_handlers__[] =
{
    collecta_ucli_ucli__clear_counters__,
    collecta_ucli_ucli__show_counters__,
    collecta_ucli_ucli__show_collectors__,
    collecta_ucli_ucli__config__,
    NULL
};
/* <auto.ucli.handlers.end> */

static ucli_module_t
collecta_ucli_module__ =
    {
        "collecta_ucli",
        NULL,
        collecta_ucli_ucli_handlers__,
        NULL,
        NULL,
    };

ucli_node_t*
collecta_ucli_node_create(void)
{
    ucli_node_t* n;
    ucli_module_init(&collecta_ucli_module__);
    n = ucli_node_create("collecta", NULL, &collecta_ucli_module__);
    ucli_node_subnode_add(n, ucli_module_log_node_create("collecta"));
    return n;
}

#else
void*
collecta_ucli_node_create(void)
{
    return NULL;
}
#endif

