
###############################################################################
#
# Inclusive Makefile for the host_sflow module.
#
# Autogenerated 2014-11-05 11:27:10.558195
#
###############################################################################
host_sflow_BASEDIR := $(dir $(abspath $(lastword $(MAKEFILE_LIST))))
include $(host_sflow_BASEDIR)/module/make.mk
include $(host_sflow_BASEDIR)/module/src/make.mk

