############################################################
# <bsn.cl fy=2013 v=none>
# 
#        Copyright 2013, 2014 BigSwitch Networks, Inc.        
# 
# 
# 
# </bsn.cl>
############################################################
ARCH=powerpc
PACKAGE_NAMES=ofad-6.3.3-release
include ../../../../../../make/debuild.mk



