ifndef SWITCHLIGHT
$(error $$SWITCHLIGHT is undefined.)
endif

SWITCHLIGHT_REQUIRED_SUBMODULES := broadcom bigcode indigo bigcode-internal infra 
SWITCHLIGHT_REQUIRED_PACKAGES := libbroadcom-5.6-release-dev:powerpc
include $(SWITCHLIGHT)/make/component.mk




