#!/bin/sh
############################################################
#
# Platform: Quanta LB9
#
############################################################

n=49
dump() {
    echo "$2 port $n:"
    hexdump -C /sys/class/i2c-dev/i2c-$1/device/$1-0050/eeprom 2>/dev/null
    n=$((n+1))
}

# Linux assigns I2C bus numbers as it enumerates the I2C master/mux
# devices in the device tree breadth-first.  The bus numbers below may
# change if the device tree changes.

for i in $(seq 1 1 4); do
    dump $i SFP
done
