ifndef SWITCHLIGHT
$(error $$SWITCHLIGHT is undefined.)
endif

# Fill me out if necessary
# SWITCHLIGHT_REQUIRED_SUBMODULES :=
# SWITCHLIGHT_REQUIRED_PACKAGES :=

include $(SWITCHLIGHT)/make/component.mk
