###############################################################################
#
# Switchlight Powerpc Release Filesystem
#
###############################################################################
ROOTFS_BUILD_DIR := $(abspath $(dir $(lastword $(MAKEFILE_LIST))))
ROOTFS_ARCH := powerpc
include $(SWITCHLIGHT)/make/rootfs.mk

