ifndef SWITCHLIGHT
$(error $$SWITCHLIGHT is undefined.)
endif

SWITCHLIGHT_REQUIRED_PACKAGES := loader-i386:i386

include $(SWITCHLIGHT)/make/component.mk


KVM_HDA := slnfs-hda.img
KVM_ISO := loader-i386.iso

include $(SWITCHLIGHT)/make/kvm.mk





