############################################################
# <bsn.cl fy=2013 v=none>
# 
#        Copyright 2013, 2014 BigSwitch Networks, Inc.        
# 
# 
# 
# </bsn.cl>
############################################################
ARCH=amd64
PACKAGE_NAMES=kernel-x86-64 kernel-x86-64-headers
include ../../../../../make/debuild.mk



