###############################################################################
#
#  Makefile
#
#  IVS Makefile
#
###############################################################################
include ../../init.mk

MODULE :=  IVS
AUTOMODULE :=  IVS

include $(BUILDER)/definemodule.mk
