############################################################
# <bsn.cl fy=2013 v=none>
# 
#        Copyright 2013, 2014 BigSwitch Networks, Inc.        
# 
# 
# 
# </bsn.cl>
############################################################
############################################################
#
#  Makefile
#
#  IVS Makefile
#
############################################################
include ../../init.mk

MODULE :=  IVS
AUTOMODULE :=  IVS

include $(BUILDER)/definemodule.mk
