ifndef ARCH
$(error $$ARCH is not specified.)
endif

ifndef BUILD_DIR_BASE
$(error $$BUILD_DIR_BASE is not specified.)
endif

PACKAGE_NAMES=brcmd-5.10.0-sim
include ../../../../../../make/debuild.mk



