###############################################################################
#
# SDK 6.2.7 Release Build Configuration
#
###############################################################################
SDK_CONFIG=release
BUILD_SDK_6_2_7_DIR := $(abspath $(dir $(lastword $(MAKEFILE_LIST))))
include ../sdk-6.2.7.mk



